[tool.poetry]
name = "app"
version = "0.0.1"
description = "FocusXgen TradeStation Client"
authors = ["AviidaTech"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "~0.15.0"
fastapi = "~0.70.0"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = "~1.8.2"}